import Head from 'next/head'
import Image from 'next/image'
import { FC, ChangeEvent,  useState } from 'react'
import styles from '../styles/Home.module.css'
import { Task } from '../interfaces'
import TodoTask from '../Components/TodoTask'
import { render } from 'react-dom'
import ClearAll from '../Components/ClearAll'

const Home: FC = () => {

  const[task, setTask] = useState<string>("");
  const[deadline, setDeadline] = useState<number>(0);
  const[todoList, setTodoList] = useState<Task[]>([]);

  const handleChange = (event: ChangeEvent<HTMLInputElement>): void => {
    if (event.target.name === "task") {
      setTask(event.target.value);
    }
    else {
      setDeadline(Number(event.target.value));
    }
  }

  const addTask = (): void => {
    const newTask = {taskName: task, deadline: deadline};
    setTodoList([...todoList, newTask]);
    setTask("");
    setDeadline(0);
  }

  const completeTask = (taskNameToDelete: string): void => {
    setTodoList(todoList.filter((task) => {
      return task.taskName != taskNameToDelete
    }))
  }

  const completeAllTasks = () : void => {
    setTodoList([])
    console.log(todoList)
  }


  return (
    <div className='flex items-center flex-col w-screen h-screen p-8 bg-cultured'>
      <Head>
        <title>To-do List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex-[30%] bg-rich-black w-full flex justify-center items-center flex-col rounded-lg mb-4'>
        <h1 className='text-cultured text-xl'>Add Task</h1>
        <div className='flex flex-col'>
          <input className='w-[200px] h-[40px] border-none pl-2.5' type="text" placeholder="Task..." name="task" value={task} onChange={handleChange}/>
          <input className='w-[200px] h-[40px] border-none pl-2.5' type="number" placeholder="Deadline (in Days)..." name="deadline" value={deadline} onChange={handleChange} />
          <button className='w-[200px] h-[40px] border-none cursor-pointer bg-strong-cyan hover:text-cultured' onClick={addTask}>Add Task</button>
        </div>
        
        
      </div>
      <div className="flex-[70%] w-full flex items-center flex-col bg-rich-black rounded-lg">
        <div>
          {todoList.length === 0 && <h1 className='p-6 text-cultured text-xl'>List Empty!</h1>}
            {todoList.map((task: Task, key: number) =>{
              return <TodoTask key={key} task={task} completeTask={completeTask}/>;
            })}
        </div>
        <div className="pt-10">
          {todoList.length > 0 && <ClearAll completeAllTasks={completeAllTasks}/>}
        </div>
      </div>
    </div>
  )
}

export default Home;